# Generated by Django 4.2.9 on 2024-01-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.user'),
        ),
    ]
